### ISSUE TITLE
Modify deck constructor for 50 cards of spanish deck

### ISSUE THREAD

**Issue by christarpher** [cs361fall2017/team16#36]
Spanish deck uses the following suits: bastos (clubs), oros (golden coins), copas (cups), and espadas (swords).
Spanish deck contains 50 cards: nine ranked cards per suit (1-9), three face cards per suit (10-12), and 2 comodines cards (Jokers).

**Comment by luthco** [comment]
This issue has been fixed.  The deck is now able to hold 50 cards, rather than 52 like before.
