### ISSUE TITLE
Edit win condition for spanish deck

### ISSUE THREAD

**Issue by christarpher** [cs361fall2017/team16#40]
In the spanish version of the game once you reach a score of 46, the win condition should be triggered. The win condition for the regular and aces version of the game should retain a win score of 48.

**Comment by Cjay84** [comment]
Since the jokers can remove the highest value card (12) in the deck as well as themselves, is the highest score possible 48 for the Spanish version as well?  The only 2 cards left in this case would be the other 2 '12 rank' cards.

**Comment by christarpher** [comment]
The win condition should be if there are 46 points. Any remaining jokers do not count for points and there can be 0, 1, or 2 jokers left with the 4 "top" cards on the table and it would be considered a win.

**Comment by luthco** [comment]
The win condition has been updated correctly.  The win condition is now set at 46 rather than 48 cards left in the deck.
